replicaCount: 1

image:
  repository: dievri/inferno-os
  pullPolicy: Always
  tag: "getauth"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: LoadBalancer
  port: 1917

ingress:
  enabled: true
  annotations:
      kubernetes.io/ingress.class: nginx
  hosts:
    - host: "in.metacoma.io"
      paths: 
        - /
  tls: []

resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1

nodeSelector: {}

tolerations: []

affinity: {}
