replicaCount: 1

image:
  repository: dievri/inferno-os
  pullPolicy: Always
  tag: "getauth"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  nodePort: 31000
  port: 31000

ingress:
  enabled: false
  annotations: 
      kubernetes.io/ingress.class: nginx
  hosts:
    - host: ""
      paths: 
        - /
  tls: []

resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1

nodeSelector: {}

tolerations: []

affinity: {}
