replicaCount: 1

image:
  repository: dievri/inferno-os
  pullPolicy: Always
  tag: "focal"

serviceAccount:
  create: false

securityContext: {}

service:
  type: ClusterIP
  port: 1918

ingress:
  enabled: false

resources: {}
autoscaling:
  enabled: false

profile: | 
  load file2chan
  load std
  ndb/cs
  for host_var in `{ os env } { '{'$host_var'}' }
  CMD_CHAN_DIR = /tmp/cmdchan

  test -d $CMD_CHAN_DIR || mkdir -p $CMD_CHAN_DIR

  dir = /
  port = 1918
  
  output_file := /tmp/output_file
  file2chan $CMD_CHAN_DIR^/cmd {
        if {~ ${rget offset} 0} {
          cat $output_file | putrdata
        } {
          rread ''
        }
      } {
        sh -c ${rget data} >$output_file >>[2]$output_file
    	}

  listen -A 'tcp!*!'$port { export $dir & } &
