replicaCount: 1

image:
  repository: dievri/webhooks
  pullPolicy: Always
  tag: cards

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: webhook.metacoma.io
      paths:
        - /
  tls: []