replicaCount: 1

image:
  repository: 9mine/minetest
  pullPolicy: Always
  tag: "master"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 30000
  nodePort: 30000
 
resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10

nodeSelector: {}

tolerations: []

affinity: {}
