apiVersion: v1
kind: Service
metadata:
  name: {{ include "minetest.fullname" . }}
  labels:
    {{- include "minetest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
      protocol: UDP
      name: http
  selector:
    {{- include "minetest.selectorLabels" . | nindent 4 }}
