---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "inferno.labels" . | nindent 4 }}
spec:
  {{- range $svc := .Values.service }}
  type: {{ $svc.type }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}  # always the same
      protocol: TCP                           # always tcp
      name: 9p-{{ $svc.port }} 
  {{- end }}    
  selector:
    {{- include "inferno.selectorLabels" . | nindent 4 }}
{{- if .Values.nodePortRange }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "inferno.fullname" . }}-nodeport
  labels:
    {{- include "inferno.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    {{- range $nPort := untilStep (int .Values.nodePortRange.from)  (int .Values.nodePortRange.to) 1 }}
    - port: {{ $nPort }}
      targetPort: {{ $nPort }}
      nodePort: {{ $nPort }}
      name: "{{ $.Release.Name }}-nodeport-{{ $nPort }}"
    {{- end }}
  selector:
    {{- include "inferno.selectorLabels" . | nindent 4 }}
{{- end }}
