apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "inferno.labels" . | nindent 4 }}
spec:
  {{- range $svc := .Values.service }}
  type: {{ $svc.type }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}  # always the same
      protocol: TCP                           # always tcp
      name: 9p-{{ $svc.port }} 
  {{- end }}    
  selector:
    {{- include "inferno.selectorLabels" . | nindent 4 }}
