apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "inferno.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1918
      protocol: TCP
      name: 9p
  selector:
    {{- include "inferno.selectorLabels" . | nindent 4 }}
