apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-auth
data:
    GITHUB_USER: {{ .Values.GITHUB_USER | b64enc }}
    GITHUB_TOKEN: {{ .Values.GITHUB_TOKEN | b64enc }}
    GITHUB_WEBHOOK_SECRET: {{ .Values.GITHUB_WEBHOOK_SECRET | b64enc }}
    GITHUB_TG_CHAT_ID: {{ .Values.GITHUB_TG_CHAT_ID | b64enc }}
    GITHUB_TG_BOT_TOKEN: {{ .Values.GITHUB_TG_BOT_TOKEN | b64enc }}

