---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-execfuse-j2-definition
data:
  fs.yml: |
    {{ .Values.fs | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-profile
data:
  profile: |
    load file2chan
    load std
    ndb/cs
    for host_var in `{ os env } { '{'$host_var'}' }
    
    dir = $EXPORT_PATH
    port = $NINEP_PUBLIC_PORT
    
    test -d /tmp || mkdir /tmp
    test -d /mnt/registry || mkdir -p /mnt/registry
    mount -A tcp!registry!registry /mnt/registry
    
    echo $NINEP_PUBLIC_HOST > /dev/sysname 
    grid/reglisten -A -r svc rstyx 'tcp!*!'^$port { export $dir &} || exit 1
