---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-execfuse-j2-definition
data:
  fs.yml: |
    {{ .Values.fs | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-profile
data:
  profile: |
    {{ .Values.profile | nindent 4 }}
---
    
