apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "9p-execfuse-jinja2.fullname" . }}
  labels:
    {{- include "9p-execfuse-jinja2.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "9p-execfuse-jinja2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "9p-execfuse-jinja2.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "9p-execfuse-jinja2.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "master" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:          
            {{- range .Values.env }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
            {{- end }}
            - name: NINEP_PUBLIC_HOST
              value: "{{ .Release.Name }}"
            - name: NINEP_PUBLIC_PORT
              value: "{{ .Values.service.port }}"
            - name: EXPORT_PATH
              value: /host/execfuse-fs
            - name: NINEP_DESCRIPTION
              value: {{ .Values.description | default "9mine module" | quote }}
          envFrom: 
              {{- if .Values.secrets }}
              - secretRef:
                  name: {{ .Release.Name }}-secrets
              {{- end }}
          volumeMounts:
            - name: devfuse
              mountPath: /dev/fuse
            - name: profile-volume
              mountPath: /usr/inferno-os/lib/sh/profile
              subPath: profile
            - name: shared-data
              mountPath: /execfuse-fs
          ports:
            - name: 9p
              containerPort: {{ .Values.service.port }}
              protocol: TCP
      initContainers:
        - name: {{ .Chart.Name }}-execfuse-jinja2
          image: {{ .Values.initContainerImage.repository }}:{{ .Values.initContainerImage.tag }}
          imagePullPolicy: {{ .Values.initContainerImage.pullPolicy | default "Always" }}
          volumeMounts:
            - name: shared-data
              mountPath: /execfuse-fs
            - name: config-volume
              mountPath: /execfuse-jinja2/fs.yml
              subPath: fs.yml
          command: ["/bin/sh"]
          args: ["-c", "cd /execfuse-jinja2 && jinja2 fs.yml | ./wrapper.sh fs | tar xvf - -C /execfuse-fs --strip 1"]
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: config-volume
          configMap: 
            name: {{ .Release.Name }}-execfuse-j2-definition
        - name: profile-volume
          configMap: 
            name: {{ .Release.Name }}-profile
        - name: shared-data
          emptyDir: {}
        - name: devfuse
          hostPath:
            path: /dev/fuse
