{{- if .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-secrets
    labels:
        {{- include "9p-execfuse-jinja2.labels" . | nindent 8 }}
data: 
    {{- range $key, $val := .Values.secrets }}
    {{ $key }}: {{ $val | b64enc }} 
    {{- end }}
{{- end }}
