apiVersion: v1
kind: Service
metadata:
  #name: {{ include "9p-execfuse-jinja2.fullname" . }}
  name: {{ .Release.Name }}
  labels:
    {{- include "9p-execfuse-jinja2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1917
      protocol: TCP
      name: 9p
  selector:
    {{- include "9p-execfuse-jinja2.selectorLabels" . | nindent 4 }}
